/* This file is automatically generated.  DO NOT EDIT! */
/* Generated from: 	NetBSD: mknative-binutils,v 1.4 2004/12/10 13:57:08 mrg Exp  */

/* This file is automatically generated.  DO NOT EDIT! */
extern ld_emulation_xfer_type ld_m88kelfnbsd_emulation;
extern ld_emulation_xfer_type ld_m88kelf_emulation;
extern ld_emulation_xfer_type ld_m88kbcs_emulation;

#define EMULATION_LIST \
  &ld_m88kelfnbsd_emulation, \
  &ld_m88kelf_emulation, \
  &ld_m88kbcs_emulation, \
  0
