#	$NetBSD: Makefile,v 1.22 2004/05/08 21:51:49 kleink Exp $

INCSDIR= /usr/include/m88k

# Generated with `ls -1 *.h | sed -e 's/$/ \\/'`
INCS=	ansi.h \
	aout_machdep.h \
        asm.h \
        asm_macro.h \
	bswap.h \
        cdefs.h \
        cmmu.h \
        cpu.h \
        db_machdep.h \
	elf_machdep.h \
        endian.h endian_machdep.h \
        float.h \
        frame.h \
        ieee.h \
        ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
        intr.h \
        kcore.h \
        limits.h \
	lock.h \
	math.h \
        m88100.h \
        m8820x.h \
	mcontext.h \
        mmu.h \
        param.h \
        pcb.h \
        pmap.h \
        pmap_table.h \
	pmc.h \
        proc.h \
        profile.h \
        psl.h \
        ptrace.h \
        reg.h \
        setjmp.h \
        signal.h \
        stdarg.h \
        trap.h \
        types.h \
	userret.h \
        va-m88k.h \
        varargs.h \
        vmparam.h \
	wchar_limits.h


.include <bsd.kinc.mk>
