#	$NetBSD: Makefile,v 1.21 2004/05/08 21:51:50 kleink Exp $

INCSDIR= /usr/include/mvme88k

INCS=	ansi.h \
        asm.h \
        asm_macro.h \
	aout_machdep.h \
        autoconf.h \
	bswap.h \
        bug.h \
        bugio.h \
        bus.h \
        cdefs.h \
        cmmu.h \
        conf.h \
        cpu.h \
        db_machdep.h \
        disklabel.h \
	elf_machdep.h \
        endian.h endian_machdep.h \
        float.h \
        frame.h \
        ieee.h \
        ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
        intr.h \
        kcore.h \
        limits.h \
	loadfile_machdep.h \
	lock.h \
	math.h \
        m88100.h \
        m88110.h \
        m8820x.h \
        m88410.h \
	mcontext.h \
        mioctl.h \
        mmu.h \
        mvme187.h \
        mvme188.h \
        param.h \
        pcb.h \
        pmap.h \
        pmap_table.h \
	pmc.h \
        proc.h \
        profile.h \
        prom.h \
        psl.h \
        ptrace.h \
        reg.h \
        setjmp.h \
        signal.h \
        stdarg.h \
        trap.h \
        types.h \
        va-m88k.h \
        varargs.h \
        vmparam.h \
	wchar_limits.h

.include <bsd.kinc.mk>
